<a href="https://colab.research.google.com/github/Nirupandey/CE888/blob/master/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 1
## first problem




In [0]:
import numpy as np
a = np.array([[0,0],
             [1,1],
             [2,2],
             [3,3]])
print(a)

[[0 0]
 [1 1]
 [2 2]
 [3 3]]


## second problem


In [0]:
def ascending_sort(x):
    for i in range(len(x)):
        swap = i + np.argmin(x[i:])
        (x[i], x[swap]) = (x[swap], x[i])
    return x

In [0]:
b = np.array([5,2,7,4,0,6,2,8,9,1])
print (b)

[5 2 7 4 0 6 2 8 9 1]


In [0]:
ascending_sort(b)

array([0, 1, 2, 2, 4, 5, 6, 7, 8, 9])

In [0]:
def descending_sort(x):
    for i in range(len(x)):
        swap = i + np.argmax(x[i:])
        (x[i], x[swap]) = (x[swap], x[i])
    return x

In [0]:
descending_sort(b)

array([9, 8, 7, 6, 5, 4, 2, 2, 1, 0])

In [0]:
c = np.arange(10).reshape(1,10) 
print(c)

[[0 1 2 3 4 5 6 7 8 9]]


##3rd problem

In [0]:
x= np.array([1,2, 3, 4, 5, 6, 7, 8, 9])
print(x)

[1 2 3 4 5 6 7 8 9]


In [0]:
np.reshape(x, (3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##4th problem

In [0]:
a = ([1,2,3])
b= ([9,8,7])
np.hstack((a, b))        ## joining horizontally

array([1, 2, 3, 9, 8, 7])

In [0]:
np.vstack((a, b))      ## joining vertically

array([[1, 2, 3],
       [9, 8, 7]])

## 5th problem

In [0]:
a5 = np.arange(12).reshape(4,3)
b5 = np.arange(12).reshape(4,3) + 5
print('a5 = ' + str(a5))
print('b5 = ' + str(b5))

a5 = [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
b5 = [[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]]


In [0]:
np.reshape(a5, (1, 12))
np.reshape(b5, (1, 12))

array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [0]:
np.intersect1d(a5, b5)

array([ 5,  6,  7,  8,  9, 10, 11])

##6th problem

In [0]:
a6= np.arange(25).reshape(5,5)
print (a6)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [0]:
c_max = np.amax(a6, axis =0)
print(c_max )

[20 21 22 23 24]


In [0]:
c_min = np.amin(a6, axis =0)
print(c_min )

[0 1 2 3 4]


In [0]:
r_max = np.amax(a6, axis =1)
print(r_max )

[ 4  9 14 19 24]


In [0]:
r_min = np.amin(a6, axis =0)
print(r_min )

[0 1 2 3 4]


##7th problem

In [0]:
a7 = np.arange(100)
print(a7)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [0]:
np.mean(a7)

49.5

In [0]:
np.median(a7)

49.5

In [0]:
np.std(a7)

28.86607004772212

##8th problem

In [0]:
from numpy import linalg as LA

In [0]:
print(a5)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [0]:
LA.norm(a5)

22.494443758403985

## 9th problem

In [0]:
a9= np.arange(48).reshape(16,3) +1
print(a9)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]
 [34 35 36]
 [37 38 39]
 [40 41 42]
 [43 44 45]
 [46 47 48]]


In [0]:
b9 = np.vsplit(a9,4)
print(b9)

[array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]]), array([[25, 26, 27],
       [28, 29, 30],
       [31, 32, 33],
       [34, 35, 36]]), array([[37, 38, 39],
       [40, 41, 42],
       [43, 44, 45],
       [46, 47, 48]])]


In [0]:
b9.shape

AttributeError: ignored